//! cli-b/b4 — the `diff` CLI differential.
//!
//! For each snapshot pair / variant in the diff manifest, deserialize the
//! vendored snapshot inputs (`tests/cli-b-goldens/diff/snapshots/`), run the
//! Rust diff engine + formatters, and byte-compare every `.human.txt` / `.json` /
//! `.sarif` golden under `tests/cli-b-goldens/diff/`. Also asserts:
//!   - the rename variant (`--renames rename-overlay.json`),
//!   - the strict-coverage exit code (1) + strict json golden,
//!   - the `--fail-on medium` exit code (1),
//!   - the ws-mode stderr note (byte-exact).
//!
//! Ungated: a divergence is a Rust bug to fix, never something to tolerate.
//!
//! Task 3.3 (al-sem parity retirement) vendored every input this file needs
//! (snapshot pairs, `rename-overlay.json`, the `ws-diff-rename` /
//! `ws-diff-removed-field` fixture trees) in-repo and regenerated every OUTPUT
//! golden from THIS engine — no al-sem checkout is read anymore, and there is
//! no skip-gate: missing inputs are a hard failure. Regenerate with
//! `REGEN_TEMP_GOLDENS=1 cargo test --test cli cli_b_diff_differential::`.

use std::path::PathBuf;

use al_sem::engine::gate::cbor::CborValue;
use al_sem::engine::gate::diff::cli::{DiffCliOptions, run_diff};
use al_sem::engine::gate::diff::format::format_diff;
use al_sem::engine::gate::diff::renames::parse_rename_overlay;
use al_sem::engine::gate::diff::{CoveragePolicy, DiffEngineOptions, Severity, run_diff_engine};
use al_sem::engine::gate::snapshot_deserialize::{SnapshotFormat, deserialize_snapshot};

use crate::regen;

const VERSION_OVERRIDE: &str = "cli-b-v1";

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Vendored fixture tree root (Task 3.3).
fn fixtures_dir() -> PathBuf {
    repo_root().join("tests").join("fixtures")
}

/// In-repo home for the cli-b diff goldens (inputs + outputs), vendored/
/// regenerated by Task 3.3.
fn goldens_dir() -> PathBuf {
    repo_root().join("tests").join("cli-b-goldens").join("diff")
}

fn snapshots_dir() -> PathBuf {
    goldens_dir().join("snapshots")
}

/// Whether `REGEN_TEMP_GOLDENS=1` is set — Rust-owned baselines are
/// regenerated from THIS engine, never copied from al-sem (retired). Delegates
/// to the shared value-gated helper (Task T0.6) rather than checking presence.
fn regen_mode() -> bool {
    regen::regen_mode()
}

fn load_snap(name: &str) -> CborValue {
    let path = snapshots_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    deserialize_snapshot(&bytes, Some(SnapshotFormat::Json))
        .unwrap_or_else(|e| panic!("deserialize {}: {e}", path.display()))
}

fn read_golden(name: &str) -> String {
    let path = goldens_dir().join(name);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read golden {}: {e}", path.display()))
}

fn assert_bytes_eq(label: &str, golden: &str, actual: &str) {
    if golden.as_bytes() != actual.as_bytes() {
        let first = golden
            .bytes()
            .zip(actual.bytes())
            .position(|(g, a)| g != a)
            .unwrap_or(golden.len().min(actual.len()));
        let ctx_g = &golden[first.saturating_sub(40)..(first + 40).min(golden.len())];
        let ctx_a = &actual[first.saturating_sub(40)..(first + 40).min(actual.len())];
        panic!(
            "{label}: BYTE MISMATCH at offset {first}\n  golden len={} actual len={}\n  golden …{ctx_g}…\n  actual …{ctx_a}…",
            golden.len(),
            actual.len()
        );
    }
}

/// Regen-or-check an OUTPUT golden: in `REGEN_TEMP_GOLDENS` mode write `actual`
/// (Rust-owned baseline, regenerated from THIS engine); otherwise byte-compare
/// against the committed in-repo golden.
fn check_or_regen_bytes(name: &str, actual: &str) {
    let path = goldens_dir().join(name);
    if regen_mode() {
        std::fs::create_dir_all(path.parent().expect("golden has a parent dir"))
            .unwrap_or_else(|e| panic!("regen mkdir for {}: {e}", path.display()));
        std::fs::write(&path, actual)
            .unwrap_or_else(|e| panic!("regen write {}: {e}", path.display()));
        eprintln!("REGEN cli-b diff golden: {}", path.display());
        return;
    }
    let golden = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read golden {}: {e}", path.display()));
    assert_bytes_eq(name, &golden, actual);
}

/// The 5 corpus pairs (snapshot-input mode, loose).
const PAIRS: &[&str] = &[
    "schema-field-removed",
    "capability-gained-http",
    "permission-rights-expanded",
    "abi-signature-changed",
    "event-added",
];

fn run_engine(
    old: &CborValue,
    new: &CborValue,
    policy: CoveragePolicy,
) -> al_sem::engine::gate::diff::DiffEngineResult {
    run_diff_engine(
        old,
        new,
        &DiffEngineOptions {
            coverage_policy: policy,
            deterministic: true,
            rename_overlay: None,
        },
    )
}

#[test]
fn diff_pairs_human_json_sarif_byte_match() {
    let empty: Vec<CborValue> = Vec::new();
    for pair in PAIRS {
        let old = load_snap(&format!("{pair}-old.snap.json"));
        let new = load_snap(&format!("{pair}-new.snap.json"));
        let result = run_engine(&old, &new, CoveragePolicy::Loose);

        let human = format_diff(&result, "human", VERSION_OVERRIDE, true, &empty);
        check_or_regen_bytes(&format!("{pair}.human.txt"), &human);

        let json = format_diff(&result, "json", VERSION_OVERRIDE, true, &empty);
        check_or_regen_bytes(&format!("{pair}.json"), &json);

        let sarif = format_diff(&result, "sarif", VERSION_OVERRIDE, true, &empty);
        check_or_regen_bytes(&format!("{pair}.sarif"), &sarif);
    }
}

#[test]
fn diff_rename_variant_from_overlay_byte_match() {
    // The rename pair's snapshots aren't committed (the dump composes them from the
    // ws-diff-rename fixture, vendored at Task 3.3). Reanalyze both sides via the
    // ws-mode path and apply the committed overlay, then byte-compare
    // rename.renamed.json.
    let fixtures = fixtures_dir().join("ws-diff-rename");
    let a = fixtures.join("a");
    let b = fixtures.join("b");
    assert!(
        a.is_dir() && b.is_dir(),
        "vendored ws-diff-rename fixture missing at {}",
        fixtures.display()
    );
    let old = compose_ws(&a);
    let new = compose_ws(&b);

    let overlay_text = read_golden("rename-overlay.json");
    let overlay = parse_rename_overlay(&overlay_text).expect("parse overlay");

    let result = run_diff_engine(
        &old,
        &new,
        &DiffEngineOptions {
            coverage_policy: CoveragePolicy::Loose,
            deterministic: true,
            rename_overlay: Some(overlay),
        },
    );
    let empty: Vec<CborValue> = Vec::new();
    let json = format_diff(&result, "json", VERSION_OVERRIDE, true, &empty);
    check_or_regen_bytes("rename.renamed.json", &json);
    let human = format_diff(&result, "human", VERSION_OVERRIDE, true, &empty);
    check_or_regen_bytes("rename.renamed.human.txt", &human);
}

fn compose_ws(dir: &std::path::Path) -> CborValue {
    use al_sem::engine::gate::model_instance_id::compute_gate_model_instance_id;
    use al_sem::engine::l5::snapshot_full::{FullSnapshotOptions, compose_full_snapshot};
    use al_sem::program::model::program_calls::assemble_and_resolve_workspace_program;
    let model_id = compute_gate_model_instance_id(dir).expect("modelInstanceId");
    let resolved = assemble_and_resolve_workspace_program(dir, &model_id, false).expect("resolve");
    let opts = FullSnapshotOptions {
        workspace_dir: dir,
        driver_version: VERSION_OVERRIDE,
        deterministic: true,
        roots_config_ignored: false,
    };
    compose_full_snapshot(&resolved, &opts)
}

#[test]
fn diff_strict_coverage_json_and_exit_byte_match() {
    let old = load_snap("coverage-strict-old.snap.json");
    let new = load_snap("coverage-strict-new.snap.json");

    // Strict json golden.
    let strict = run_engine(&old, &new, CoveragePolicy::Strict);
    let empty: Vec<CborValue> = Vec::new();
    let json = format_diff(&strict, "json", VERSION_OVERRIDE, true, &empty);
    check_or_regen_bytes("coverage-strict.strict.json", &json);

    // Strict exit code = 1 (coverage-incomplete) — driven for real via the CLI
    // orchestrator so the golden text reflects an actually-computed exit code.
    let old_path = snapshots_dir().join("coverage-strict-old.snap.json");
    let new_path = snapshots_dir().join("coverage-strict-new.snap.json");
    let old_s = old_path.to_string_lossy().to_string();
    let new_s = new_path.to_string_lossy().to_string();
    let strict_outcome = run_diff(&DiffCliOptions {
        old_arg: &old_s,
        new_arg: &new_s,
        format: "json",
        out: None,
        coverage_policy: CoveragePolicy::Strict,
        renames_path: None,
        fail_on: None,
        strict: false,
        deterministic: true,
        driver_version: VERSION_OVERRIDE,
    });
    assert_eq!(strict_outcome.exit_code, 1, "strict CLI exit must be 1");
    check_or_regen_bytes(
        "coverage-strict.strict.exitcode.txt",
        &format!("{}\n", strict_outcome.exit_code),
    );
    let strict_failed = strict
        .diagnostics
        .iter()
        .any(|d| d.kind == "coverage-incomplete");
    assert!(
        strict_failed,
        "strict run must produce a coverage-incomplete diagnostic"
    );

    // Loose json + human goldens.
    let loose = run_engine(&old, &new, CoveragePolicy::Loose);
    let loose_json = format_diff(&loose, "json", VERSION_OVERRIDE, true, &empty);
    check_or_regen_bytes("coverage-strict.loose.json", &loose_json);
    let loose_human = format_diff(&loose, "human", VERSION_OVERRIDE, true, &empty);
    check_or_regen_bytes("coverage-strict.loose.human.txt", &loose_human);

    // fail-on medium exit code = 1 — also driven for real via the CLI orchestrator.
    let failon_outcome = run_diff(&DiffCliOptions {
        old_arg: &old_s,
        new_arg: &new_s,
        format: "human",
        out: None,
        coverage_policy: CoveragePolicy::Loose,
        renames_path: None,
        fail_on: Some(Severity::Medium),
        strict: false,
        deterministic: true,
        driver_version: VERSION_OVERRIDE,
    });
    assert_eq!(
        failon_outcome.exit_code, 1,
        "fail-on medium CLI exit must be 1"
    );
    check_or_regen_bytes(
        "coverage-strict.failon.exitcode.txt",
        &format!("{}\n", failon_outcome.exit_code),
    );
    let t = Severity::Medium.rank();
    let triggers = loose.findings.iter().any(|f| f.severity.rank() <= t);
    assert!(
        triggers,
        "fail-on medium must trigger on the loose findings"
    );
}

#[test]
fn diff_strict_exit_via_cli_orchestrator() {
    // Drive the full CLI orchestrator (run_diff) so the exit-gate wiring is covered.
    let old_path = snapshots_dir().join("coverage-strict-old.snap.json");
    let new_path = snapshots_dir().join("coverage-strict-new.snap.json");
    let old_s = old_path.to_string_lossy().to_string();
    let new_s = new_path.to_string_lossy().to_string();

    // strict → exit 1.
    let outcome = run_diff(&DiffCliOptions {
        old_arg: &old_s,
        new_arg: &new_s,
        format: "json",
        out: None,
        coverage_policy: CoveragePolicy::Strict,
        renames_path: None,
        fail_on: None,
        strict: false,
        deterministic: true,
        driver_version: VERSION_OVERRIDE,
    });
    assert_eq!(outcome.exit_code, 1, "strict CLI exit must be 1");
    assert!(outcome.error_message.is_none());

    // fail-on medium → exit 1.
    let outcome = run_diff(&DiffCliOptions {
        old_arg: &old_s,
        new_arg: &new_s,
        format: "human",
        out: None,
        coverage_policy: CoveragePolicy::Loose,
        renames_path: None,
        fail_on: Some(Severity::Medium),
        strict: false,
        deterministic: true,
        driver_version: VERSION_OVERRIDE,
    });
    assert_eq!(outcome.exit_code, 1, "fail-on medium CLI exit must be 1");
}

#[test]
fn diff_app_input_rejected() {
    // A `.app` argument is rejected cleanly (CONFIG_ERROR), not a panic. Use a real
    // file path that ends with .app by pointing at any existing file renamed in mind;
    // simplest: create a temp .app file.
    let tmp = std::env::temp_dir().join("alsem-diff-test.app");
    std::fs::write(&tmp, b"not a real app").expect("write temp .app");
    let tmp_s = tmp.to_string_lossy().to_string();
    let outcome = run_diff(&DiffCliOptions {
        old_arg: &tmp_s,
        new_arg: &tmp_s,
        format: "json",
        out: None,
        coverage_policy: CoveragePolicy::Loose,
        renames_path: None,
        fail_on: None,
        strict: false,
        deterministic: true,
        driver_version: VERSION_OVERRIDE,
    });
    let _ = std::fs::remove_file(&tmp);
    assert_eq!(outcome.exit_code, 2, "app input → CONFIG_ERROR exit 2");
    assert!(outcome.error_message.is_some());
    assert!(outcome.output.is_none());
}

#[test]
fn diff_ws_mode_stderr_note_byte_match() {
    // The ws-mode stderr note must be byte-exact. Drive run_diff over the two
    // fixture directories and compare its first stderr line to the golden.
    let fixture = fixtures_dir().join("ws-diff-removed-field");
    let a = fixture.join("a");
    let b = fixture.join("b");
    assert!(
        a.is_dir() && b.is_dir(),
        "vendored ws-diff-removed-field fixture missing at {}",
        fixture.display()
    );
    let a_s = a.to_string_lossy().to_string();
    let b_s = b.to_string_lossy().to_string();
    let outcome = run_diff(&DiffCliOptions {
        old_arg: &a_s,
        new_arg: &b_s,
        format: "human",
        out: None,
        coverage_policy: CoveragePolicy::Loose,
        renames_path: None,
        fail_on: None,
        strict: false,
        deterministic: true,
        driver_version: VERSION_OVERRIDE,
    });

    // stderr golden has a trailing newline; our stderr_lines join with newline + the
    // bin adds one per line. Compare the note line text.
    assert_eq!(
        outcome.stderr_lines.len(),
        1,
        "ws-mode emits exactly the note"
    );
    check_or_regen_bytes(
        "ws-mode-schema-field-removed.stderr.txt",
        &format!("{}\n", outcome.stderr_lines[0]),
    );

    // stdout (human) byte-match.
    check_or_regen_bytes(
        "ws-mode-schema-field-removed.stdout.txt",
        outcome.output.as_ref().expect("ws-mode stdout"),
    );
}

/// CBOR / cbor.gz round-trip oracle over a REAL committed snapshot: load the JSON
/// snapshot, re-encode it to CBOR (B0) and cbor.gz, decode both back, and assert
/// the diff engine produces a byte-identical json golden from the round-tripped
/// trees. This locks the deserializer's CBOR + gunzip paths against real snapshot
/// data (the committed inputs are JSON, so CBOR is otherwise corpus-invisible).
#[test]
fn cbor_and_gz_roundtrip_drives_identical_diff() {
    if regen_mode() {
        // This test only VALIDATES round-trip parity against the golden that
        // `diff_pairs_human_json_sarif_byte_match` owns/regenerates; it never
        // writes goldens itself, so it has nothing to do in regen mode.
        eprintln!(
            "cbor_and_gz_roundtrip_drives_identical_diff: skipped in REGEN_TEMP_GOLDENS mode"
        );
        return;
    }
    use al_sem::engine::l5::snapshot_full::{serialize_cbor, serialize_cbor_gz};

    let empty: Vec<CborValue> = Vec::new();
    let pair = "abi-signature-changed";
    let old_json = load_snap(&format!("{pair}-old.snap.json"));
    let new_json = load_snap(&format!("{pair}-new.snap.json"));

    // JSON → tree → CBOR → decode → tree' ; and via cbor.gz.
    let old_cbor = serialize_cbor(&old_json);
    let new_cbor = serialize_cbor(&new_json);
    let old_from_cbor =
        deserialize_snapshot(&old_cbor, Some(SnapshotFormat::Cbor)).expect("decode cbor old");
    let new_from_cbor =
        deserialize_snapshot(&new_cbor, Some(SnapshotFormat::Cbor)).expect("decode cbor new");

    let old_gz = serialize_cbor_gz(&old_json);
    let new_gz = serialize_cbor_gz(&new_json);
    let old_from_gz =
        deserialize_snapshot(&old_gz, Some(SnapshotFormat::CborGz)).expect("decode gz old");
    let new_from_gz =
        deserialize_snapshot(&new_gz, Some(SnapshotFormat::CborGz)).expect("decode gz new");

    let golden = read_golden(&format!("{pair}.json"));

    for (label, o, n) in [
        ("cbor", &old_from_cbor, &new_from_cbor),
        ("cbor.gz", &old_from_gz, &new_from_gz),
    ] {
        let result = run_engine(o, n, CoveragePolicy::Loose);
        let json = format_diff(&result, "json", VERSION_OVERRIDE, true, &empty);
        assert_bytes_eq(&format!("{pair}.json (via {label})"), &golden, &json);
    }

    // Auto-detect path (no hint): gz magic 1f 8b, cbor magic b9.
    let auto_gz = deserialize_snapshot(&old_gz, None).expect("auto gz");
    let auto_cbor = deserialize_snapshot(&old_cbor, None).expect("auto cbor");
    let r1 = run_engine(&auto_gz, &new_from_gz, CoveragePolicy::Loose);
    let r2 = run_engine(&auto_cbor, &new_from_cbor, CoveragePolicy::Loose);
    assert_bytes_eq(
        &format!("{pair}.json (auto gz)"),
        &golden,
        &format_diff(&r1, "json", VERSION_OVERRIDE, true, &empty),
    );
    assert_bytes_eq(
        &format!("{pair}.json (auto cbor)"),
        &golden,
        &format_diff(&r2, "json", VERSION_OVERRIDE, true, &empty),
    );
}

// ===========================================================================
// Synthetic oracles — lock the corpus-invisible branches (preflight fatals, the
// higher-severity finding kinds, the human zero-findings-with-diagnostics
// early-exit). Each builds a minimal CborValue snapshot tree by hand and runs the
// engine, asserting the TS-exact behavior.
// ===========================================================================

use indexmap::IndexMap;

/// Build a CborValue::Map from (key, value) pairs.
fn obj(pairs: Vec<(&str, CborValue)>) -> CborValue {
    let mut m: IndexMap<String, CborValue> = IndexMap::new();
    for (k, v) in pairs {
        m.insert(k.to_string(), v);
    }
    CborValue::Map(m)
}

fn txt(s: &str) -> CborValue {
    CborValue::Text(s.to_string())
}

/// A minimal snapshot with a given set of top-level fact arrays. `schemaVersion`
/// defaults to 3 and `apps` to a single app guid `appguid-1` unless overridden.
fn snapshot(extra: Vec<(&str, CborValue)>) -> CborValue {
    let mut pairs: Vec<(&str, CborValue)> = vec![
        ("schemaVersion", CborValue::Int(3)),
        ("alsemVersion", txt("cli-b-v1")),
        (
            "apps",
            CborValue::Array(vec![obj(vec![("appGuid", txt("appguid-1"))])]),
        ),
        (
            "identities",
            obj(vec![
                ("stableIds", CborValue::Array(vec![])),
                ("displayNames", CborValue::Array(vec![])),
            ]),
        ),
    ];
    pairs.extend(extra);
    obj(pairs)
}

fn engine(
    old: &CborValue,
    new: &CborValue,
    policy: CoveragePolicy,
) -> al_sem::engine::gate::diff::DiffEngineResult {
    run_diff_engine(
        old,
        new,
        &DiffEngineOptions {
            coverage_policy: policy,
            deterministic: true,
            rename_overlay: None,
        },
    )
}

fn find_kind<'a>(
    r: &'a al_sem::engine::gate::diff::DiffEngineResult,
    kind: &str,
) -> &'a al_sem::engine::gate::diff::DiffFinding {
    r.findings
        .iter()
        .find(|f| f.kind.as_str() == kind)
        .unwrap_or_else(|| {
            panic!(
                "no finding of kind {kind}; got {:?}",
                r.findings
                    .iter()
                    .map(|f| f.kind.as_str())
                    .collect::<Vec<_>>()
            )
        })
}

/// #5(a) — schemaVersion mismatch → fatal: empty findings + schema-version-mismatch diag.
#[test]
fn oracle_preflight_schema_version_mismatch_is_fatal() {
    let old = snapshot(vec![]);
    let mut new = snapshot(vec![]);
    if let CborValue::Map(m) = &mut new {
        m.insert("schemaVersion".into(), CborValue::Int(3)); // keep new at 3...
    }
    // ...but make OLD differ by mutating its schemaVersion to a sentinel. The
    // deserializer gate rejects ≠3 inputs, but the engine itself must still
    // short-circuit on a mismatch, so we feed the engine directly.
    let mut old_mut = old;
    if let CborValue::Map(m) = &mut old_mut {
        m.insert("schemaVersion".into(), CborValue::Int(99));
    }
    let r = engine(&old_mut, &new, CoveragePolicy::Loose);
    assert!(r.findings.is_empty(), "fatal preflight → no findings");
    assert!(
        r.diagnostics
            .iter()
            .any(|d| d.kind == "schema-version-mismatch")
    );
}

/// #5(b) — alsemVersion mismatch under strict → fatal error diagnostic.
#[test]
fn oracle_preflight_alsem_version_mismatch_strict_is_fatal() {
    let old = snapshot(vec![]);
    let mut new = snapshot(vec![]);
    if let CborValue::Map(m) = &mut new {
        m.insert("alsemVersion".into(), txt("cli-b-v2"));
    }
    let r = engine(&old, &new, CoveragePolicy::Strict);
    assert!(
        r.findings.is_empty(),
        "strict version mismatch → fatal, no findings"
    );
    let diag = r
        .diagnostics
        .iter()
        .find(|d| d.kind == "alsem-version-mismatch")
        .expect("alsem-version-mismatch diag");
    let sev = diag
        .fields
        .iter()
        .find(|(k, _)| k == "severity")
        .map(|(_, v)| v);
    assert!(matches!(sev, Some(CborValue::Text(s)) if s == "error"));

    // Under loose the same mismatch is a WARNING and NOT fatal (findings still flow).
    let r2 = engine(&old, &new, CoveragePolicy::Loose);
    let diag2 = r2
        .diagnostics
        .iter()
        .find(|d| d.kind == "alsem-version-mismatch")
        .expect("alsem-version-mismatch diag (loose)");
    let sev2 = diag2
        .fields
        .iter()
        .find(|(k, _)| k == "severity")
        .map(|(_, v)| v);
    assert!(matches!(sev2, Some(CborValue::Text(s)) if s == "warning"));
}

/// #5(c) — apps[0].appGuid mismatch → fatal app-identity-mismatch.
#[test]
fn oracle_preflight_app_identity_mismatch_is_fatal() {
    let old = snapshot(vec![]);
    let mut new = snapshot(vec![]);
    if let CborValue::Map(m) = &mut new {
        m.insert(
            "apps".into(),
            CborValue::Array(vec![obj(vec![("appGuid", txt("appguid-2"))])]),
        );
    }
    let r = engine(&old, &new, CoveragePolicy::Loose);
    assert!(r.findings.is_empty(), "app mismatch → fatal, no findings");
    assert!(
        r.diagnostics
            .iter()
            .any(|d| d.kind == "app-identity-mismatch")
    );
}

/// #4 — human renderer: a diff yielding DIAGNOSTICS but ZERO findings prints the
/// diagnostics block and SKIPS the `Diff: 0 finding(s)…` summary line. We synthesize
/// this via a strict run whose only coverage-sensitive finding is dropped (leaving a
/// coverage-incomplete policy diagnostic and zero findings).
#[test]
fn oracle_human_zero_findings_with_diagnostics_skips_summary() {
    // OLD has a table capability fact under a routine whose NEW-side cone is
    // partial; strict drops the lost-capability finding and emits a coverage diag.
    let subject = "appguid-1:Codeunit:50100#abc";
    let cap_fact = |op: &str| {
        obj(vec![
            ("subject", txt(subject)),
            ("op", txt(op)),
            ("resourceKind", txt("table")),
            ("resourceId", txt("appguid-1/table/50100")),
        ])
    };
    let coverage = |inherited: &str| {
        obj(vec![
            ("subject", txt(subject)),
            ("inheritedStatus", txt(inherited)),
        ])
    };
    let old = snapshot(vec![
        (
            "capabilityFacts",
            CborValue::Array(vec![cap_fact("insert")]),
        ),
        ("coverage", CborValue::Array(vec![coverage("complete")])),
    ]);
    // NEW: the capability is gone AND the cone is partial → strict drops the finding.
    let new = snapshot(vec![
        ("capabilityFacts", CborValue::Array(vec![])),
        ("coverage", CborValue::Array(vec![coverage("partial")])),
    ]);

    let r = engine(&old, &new, CoveragePolicy::Strict);
    assert!(r.findings.is_empty(), "strict drops the only finding");
    assert!(
        r.diagnostics
            .iter()
            .any(|d| d.kind == "coverage-incomplete"),
        "must have a coverage-incomplete diagnostic"
    );

    let empty: Vec<CborValue> = Vec::new();
    let human = format_diff(&r, "human", VERSION_OVERRIDE, true, &empty);
    assert!(
        human.contains("diagnostics:"),
        "human must print the diagnostics block, got:\n{human}"
    );
    assert!(
        !human.contains("Diff:") && !human.contains("finding(s)"),
        "human must SKIP the summary line when findings are empty, got:\n{human}"
    );
}

/// #7 — higher-severity finding kinds (corpus-invisible). Assert each kind's
/// severity + that it fires, across the families the spec reviewer enumerated.
#[test]
fn oracle_higher_severity_finding_kinds() {
    let empty: Vec<CborValue> = Vec::new();

    // -- ABI: object-removed (critical), object-accessibility-narrowed (critical) --
    let obj_fact = |sid: &str, vis: &str| {
        obj(vec![
            ("kind", txt("object")),
            ("stableId", txt(sid)),
            ("visibility", txt(vis)),
            ("signatureFingerprint", txt("sig1")),
        ])
    };
    let old = snapshot(vec![(
        "contractFacts",
        CborValue::Array(vec![
            obj_fact("appguid-1:Codeunit:1", "public"),
            obj_fact("appguid-1:Codeunit:2", "public"),
        ]),
    )]);
    let new = snapshot(vec![(
        "contractFacts",
        CborValue::Array(vec![
            // Codeunit:1 removed; Codeunit:2 narrowed public→internal.
            obj_fact("appguid-1:Codeunit:2", "internal"),
        ]),
    )]);
    let r = engine(&old, &new, CoveragePolicy::Loose);
    assert_eq!(find_kind(&r, "object-removed").severity, Severity::Critical);
    assert_eq!(
        find_kind(&r, "object-accessibility-narrowed").severity,
        Severity::Critical
    );

    // -- Schema: table-field-type-narrowed (critical), enum-value-renumbered (critical) --
    let field = |sid: &str, fp: &str| {
        obj(vec![
            ("kind", txt("field")),
            ("stableId", txt(sid)),
            ("shapeFingerprint", txt(fp)),
        ])
    };
    let enumv = |sid: &str, fp: &str| {
        obj(vec![
            ("kind", txt("enum-value")),
            ("stableId", txt(sid)),
            ("shapeFingerprint", txt(fp)),
        ])
    };
    let old = snapshot(vec![(
        "schemaFacts",
        CborValue::Array(vec![
            field("appguid-1:Table:1#1", "fpA"),
            enumv("appguid-1:Enum:1#0", "fpE0"),
        ]),
    )]);
    let new = snapshot(vec![(
        "schemaFacts",
        CborValue::Array(vec![
            field("appguid-1:Table:1#1", "fpB"),
            enumv("appguid-1:Enum:1#0", "fpE1"),
        ]),
    )]);
    let r = engine(&old, &new, CoveragePolicy::Loose);
    assert_eq!(
        find_kind(&r, "table-field-type-narrowed").severity,
        Severity::Critical
    );
    assert_eq!(
        find_kind(&r, "enum-value-renumbered").severity,
        Severity::Critical
    );

    // -- Events: publisher-signature-changed (critical, no subscribers) --
    let publisher = |routine: &str, event_id: &str| {
        obj(vec![
            ("kind", txt("publisher")),
            ("routine", txt(routine)),
            ("eventId", txt(event_id)),
        ])
    };
    let old = snapshot(vec![(
        "eventDeclarations",
        CborValue::Array(vec![publisher(
            "appguid-1:Codeunit:9#r",
            "appguid-1:Codeunit:9::OnDone::hashA",
        )]),
    )]);
    let new = snapshot(vec![(
        "eventDeclarations",
        CborValue::Array(vec![publisher(
            "appguid-1:Codeunit:9#r",
            "appguid-1:Codeunit:9::OnDone::hashB",
        )]),
    )]);
    let r = engine(&old, &new, CoveragePolicy::Loose);
    assert_eq!(
        find_kind(&r, "event-publisher-signature-changed").severity,
        Severity::Critical
    );

    // -- Capabilities: gained-commit (high) --
    let commit = obj(vec![
        ("subject", txt("appguid-1:Codeunit:7#c")),
        ("op", txt("commit")),
        ("resourceKind", txt("transaction")),
    ]);
    let old = snapshot(vec![("capabilityFacts", CborValue::Array(vec![]))]);
    let new = snapshot(vec![("capabilityFacts", CborValue::Array(vec![commit]))]);
    let r = engine(&old, &new, CoveragePolicy::Loose);
    assert_eq!(
        find_kind(&r, "capability-gained-commit").severity,
        Severity::High
    );

    // -- Permissions: rights-contracted (low), target-removed (low) --
    let perm = |target: &str, rights: Vec<&str>| {
        obj(vec![
            ("kind", txt("required")),
            ("subject", txt("appguid-1:Codeunit:5#p")),
            ("target", txt(target)),
            ("targetKind", txt("TableData")),
            (
                "rights",
                CborValue::Array(rights.iter().map(|r| txt(r)).collect()),
            ),
        ])
    };
    let old = snapshot(vec![(
        "permissionFacts",
        CborValue::Array(vec![
            perm("appguid-1:Table:1", vec!["R", "I", "M"]),
            perm("appguid-1:Table:2", vec!["R"]),
        ]),
    )]);
    let new = snapshot(vec![(
        "permissionFacts",
        CborValue::Array(vec![
            // Table:1 contracted R,I,M → R; Table:2 removed.
            perm("appguid-1:Table:1", vec!["R"]),
        ]),
    )]);
    let r = engine(&old, &new, CoveragePolicy::Loose);
    assert_eq!(
        find_kind(&r, "permission-rights-contracted").severity,
        Severity::Low
    );
    assert_eq!(
        find_kind(&r, "permission-target-removed").severity,
        Severity::Low
    );

    // Sanity: SARIF level mapping for a critical/high/low set is error/error/note.
    let sarif = format_diff(&r, "sarif", VERSION_OVERRIDE, true, &empty);
    assert!(sarif.contains("\"level\": \"note\""), "low → note in sarif");
}
