//! R3a-1 Task 2 — L4 COMBINED-GRAPH + Tarjan SCC vector parity.
//!
//! Loads the committed `tests/r3a1-vectors/r3a1-vectors.json` (generated by the
//! real al-sem L4: `indexWorkspace → resolveModel ONCE → buildCombinedGraph →
//! tarjanScc → projectR3a1`; READ-ONLY, captured POST-buildCombinedGraph/
//! POST-tarjanScc/PRE-computeSummaries, no dep hooks) and asserts, for each vector:
//! the Rust `project_r3a1_combined_graph` output's `combinedEdges` / `uncertaintyEdges`
//! / `typedEdges` / `sccs` match the expected projection BYTE-FOR-BYTE (as JSON
//! values — field presence + order + the reverse-topo SCC order all compared).
//!
//! The 4 vectors cover: the edge-kind enumeration (direct / method / codeunit-run /
//! interface multi-edge / implicit-trigger / event-dispatch / dynamic + the
//! dynamic-dispatch + unresolved-call + interface-open-world uncertainties + typed
//! edges with NO sourceAnchor); a size-1 RECURSIVE self-loop SCC; a size-2 RECURSIVE
//! mutual-recursion SCC; and a reverse-topological singleton chain.
//!
//! The vectors are the ORACLE: a failure means the Rust port diverged from al-sem,
//! and the fix is in the Rust code (NEVER the vector).
//!
//! Reproduction context (from the vector doc header):
//!   - appGuid          = "3a100000-0000-0000-0000-00000000003a"
//!   - modelInstanceId  = "r0"
//!   - files            = [[name, source], ...]  →  sourceUnitId = "ws:<name>.al"
//!     (engine-switch S9.5c: the program-backed builder reads `.al` files only;
//!     no expected value depends on the unit id)

use al_sem::program::model::program_calls::assemble_and_resolve_inline_program as assemble_and_resolve;
use serde_json::{Value, json};

const MODEL_INSTANCE_ID: &str = "r0";

#[derive(serde::Deserialize)]
struct VectorsDoc {
    #[serde(rename = "appGuid")]
    app_guid: String,
    #[serde(rename = "vectorCount")]
    vector_count: usize,
    vectors: Vec<Vector>,
}

#[derive(serde::Deserialize)]
struct Vector {
    name: String,
    /// `[[filename, source], ...]`
    files: Vec<Vec<String>>,
    expected: Expected,
}

#[derive(serde::Deserialize)]
struct Expected {
    #[serde(rename = "combinedEdges")]
    combined_edges: Vec<Value>,
    #[serde(rename = "uncertaintyEdges")]
    uncertainty_edges: Vec<Value>,
    #[serde(rename = "typedEdges")]
    typed_edges: Vec<Value>,
    sccs: Vec<Value>,
}

fn load_vectors() -> VectorsDoc {
    let raw = include_str!("../r3a1-vectors/r3a1-vectors.json");
    serde_json::from_str(raw).expect("r3a1-vectors.json parses into VectorsDoc")
}

/// The vector's files for the program-backed builder (engine-switch S9.5c),
/// which reads only `.al` files: a fixture name without the extension gets it.
fn files_of(files: &[Vec<String>]) -> Vec<(String, String)> {
    files
        .iter()
        .map(|pair| {
            assert_eq!(pair.len(), 2, "each file entry is [name, source]");
            let name = if pair[0].ends_with(".al") {
                pair[0].clone()
            } else {
                format!("{}.al", pair[0])
            };
            (name, pair[1].clone())
        })
        .collect()
}

#[test]
fn all_r3a1_combined_graph_vectors_match() {
    let doc = load_vectors();
    assert_eq!(
        doc.vector_count,
        doc.vectors.len(),
        "vectorCount agrees with the array length"
    );

    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.vectors {
        let files = files_of(&vec.files);
        let resolved = assemble_and_resolve(&files, &doc.app_guid, MODEL_INSTANCE_ID);
        let projection = resolved.project_r3a1_combined_graph();

        compare(
            &vec.name,
            "combinedEdges",
            &serde_json::to_value(&projection.combined_edges).unwrap(),
            &Value::Array(vec.expected.combined_edges.clone()),
            &mut failures,
        );
        compare(
            &vec.name,
            "uncertaintyEdges",
            &serde_json::to_value(&projection.uncertainty_edges).unwrap(),
            &Value::Array(vec.expected.uncertainty_edges.clone()),
            &mut failures,
        );
        compare(
            &vec.name,
            "typedEdges",
            &serde_json::to_value(&projection.typed_edges).unwrap(),
            &Value::Array(vec.expected.typed_edges.clone()),
            &mut failures,
        );
        compare(
            &vec.name,
            "sccs",
            &serde_json::to_value(&projection.sccs).unwrap(),
            &Value::Array(vec.expected.sccs.clone()),
            &mut failures,
        );
    }

    assert!(
        failures.is_empty(),
        "R3a-1 combined-graph vector parity failures ({}):\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}

fn compare(
    name: &str,
    surface: &str,
    actual: &Value,
    expected: &Value,
    failures: &mut Vec<String>,
) {
    if actual != expected {
        failures.push(format!(
            "[{name}] {surface} mismatch\n  expected: {}\n  actual:   {}",
            serde_json::to_string_pretty(expected).unwrap(),
            serde_json::to_string_pretty(actual).unwrap()
        ));
    }
}

/// Guard: the typed edges carry NO `sourceAnchor` / `publishAnchor` /
/// `subscriberAnchor` (dropped at the R3a-1 surface). A structural check
/// independent of the per-vector byte compare.
#[test]
fn typed_edges_carry_no_anchors() {
    let doc = load_vectors();
    let _ = json!({}); // keep serde_json::json import meaningful if compare changes
    for vec in &doc.vectors {
        let files = files_of(&vec.files);
        let resolved = assemble_and_resolve(&files, &doc.app_guid, MODEL_INSTANCE_ID);
        let projection = resolved.project_r3a1_combined_graph();
        let v = serde_json::to_value(&projection.typed_edges).unwrap();
        let s = serde_json::to_string(&v).unwrap();
        for forbidden in ["sourceAnchor", "publishAnchor", "subscriberAnchor"] {
            assert!(
                !s.contains(forbidden),
                "[{}] typedEdges must not carry {forbidden}",
                vec.name
            );
        }
    }
}
