//! R3a-2 Task 2 — JACOBI fixed-point summary core vector parity.
//!
//! Loads the committed `tests/r3a2-vectors/r3a2-vectors.json` (generated by the
//! real al-sem L4: `indexWorkspace → resolveModel → buildCombinedGraph →
//! computeSummaries via runSummaries → projectR3a2/projectR3a2Trace`; captured
//! POST-computeSummaries, no dep hooks, no capabilityFacts/coverage — this
//! describes the al-sem-side capture only; the Rust side never had a
//! `projectR3a2Trace` consumer beyond the now-deleted `r3a2_trace_vectors.rs`,
//! retired with the old Jacobi db-effect solver) and asserts, for each
//! pipeline vector:
//!   - the Rust `project_r3a2_summary_core` output's `summaries` array matches
//!     the expected projection BYTE-FOR-BYTE (as JSON values).
//!
//! Also asserts the LATTICE vectors (effectKeyOf + mergeVia) against the
//! hand-authored invariant table in the vector doc.
//!
//! The vectors are the ORACLE: a failure means the Rust port diverged from al-sem,
//! and the fix is in the Rust code (NEVER the vector).

use al_sem::engine::l4::effect_lattice::{TempStateKind, effect_key_of, merge_via};
use al_sem::engine::l4::summary::project_r3a2;
use al_sem::program::model::program_calls::assemble_and_resolve_inline_program as assemble_and_resolve;
use serde_json::Value;

const MODEL_INSTANCE_ID: &str = "r0";

// ---------------------------------------------------------------------------
// Vector document shape.
// ---------------------------------------------------------------------------

#[derive(serde::Deserialize)]
struct VectorsDoc {
    #[serde(rename = "appGuid")]
    app_guid: String,
    #[serde(rename = "pipelineVectors")]
    pipeline_vectors: Vec<PipelineVector>,
    #[serde(rename = "effectKeyVectors")]
    effect_key_vectors: Vec<EffectKeyVector>,
    #[serde(rename = "mergeViaVectors")]
    merge_via_vectors: Vec<MergeViaVector>,
}

#[derive(serde::Deserialize)]
struct PipelineVector {
    name: String,
    files: Vec<Vec<String>>,
    expected: PipelineExpected,
    // `expectedTrace` is intentionally NOT deserialized here — the JACOBI trace
    // validation (formerly `r3a2_trace_vectors.rs`) retired with the old Jacobi
    // db-effect solver; the closed-form v2 solver has no per-pass trajectory to
    // trace (see `tests/l4_summary_differential.rs`'s module doc). serde ignores
    // the unmatched key.
}

#[derive(serde::Deserialize)]
struct PipelineExpected {
    summaries: Vec<Value>,
}

#[derive(serde::Deserialize)]
struct EffectKeyVector {
    name: String,
    input: EffectKeyInput,
    #[serde(rename = "expectedKey")]
    expected_key: String,
}

#[derive(serde::Deserialize)]
struct EffectKeyInput {
    op: String,
    #[serde(rename = "tableId")]
    table_id: String,
    #[serde(rename = "operationId")]
    operation_id: String,
    #[serde(rename = "tempState")]
    temp_state: Value,
}

#[derive(serde::Deserialize)]
struct MergeViaVector {
    a: String,
    b: String,
    expected: String,
}

fn load_vectors() -> VectorsDoc {
    let raw = include_str!("../r3a2-vectors/r3a2-vectors.json");
    serde_json::from_str(raw).expect("r3a2-vectors.json parses into VectorsDoc")
}

/// The vector's files for the program-backed builder (engine-switch S9.5c),
/// which reads only `.al` files: a fixture name without the extension gets it.
fn files_of(files: &[Vec<String>]) -> Vec<(String, String)> {
    files
        .iter()
        .map(|pair| {
            assert_eq!(pair.len(), 2, "each file entry is [name, source]");
            let name = if pair[0].ends_with(".al") {
                pair[0].clone()
            } else {
                format!("{}.al", pair[0])
            };
            (name, pair[1].clone())
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Lattice unit vectors: effectKeyOf + mergeVia.
// ---------------------------------------------------------------------------

#[test]
fn effect_key_vectors_match() {
    let doc = load_vectors();
    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.effect_key_vectors {
        // Parse tempState from the JSON shape used in the vector.
        let ts = parse_temp_state_json(&vec.input.temp_state);
        let actual = effect_key_of(
            &vec.input.op,
            &vec.input.table_id,
            &vec.input.operation_id,
            &ts,
        );
        if actual != vec.expected_key {
            failures.push(format!(
                "[{}] effectKey mismatch\n  expected: {}\n  actual:   {}",
                vec.name, vec.expected_key, actual
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "effectKey vector failures ({}):\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}

#[test]
fn merge_via_vectors_match() {
    let doc = load_vectors();
    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.merge_via_vectors {
        let actual = merge_via(&vec.a, &vec.b);
        if actual != vec.expected {
            failures.push(format!(
                "[{} × {}] mergeVia mismatch\n  expected: {}\n  actual:   {}",
                vec.a, vec.b, vec.expected, actual
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "mergeVia vector failures ({}):\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}

// ---------------------------------------------------------------------------
// Pipeline vectors: full pipeline parity.
// ---------------------------------------------------------------------------

#[test]
fn all_r3a2_pipeline_vectors_match() {
    let doc = load_vectors();
    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.pipeline_vectors {
        let files = files_of(&vec.files);
        let resolved = assemble_and_resolve(&files, &doc.app_guid, MODEL_INSTANCE_ID);
        let projection = project_r3a2(&resolved);

        let actual_summaries = serde_json::to_value(&projection.summaries).unwrap();
        let expected_summaries = Value::Array(vec.expected.summaries.clone());

        if actual_summaries != expected_summaries {
            failures.push(format!(
                "[{}] summaries mismatch\n  expected: {}\n  actual:   {}",
                vec.name,
                serde_json::to_string_pretty(&expected_summaries).unwrap(),
                serde_json::to_string_pretty(&actual_summaries).unwrap()
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "R3a-2 pipeline vector parity failures ({}):\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}

// ---------------------------------------------------------------------------
// Helper: parse the JSON tempState shape into the lattice TempStateKind.
// ---------------------------------------------------------------------------

fn parse_temp_state_json(v: &Value) -> TempStateKind {
    let kind = v.get("kind").and_then(|k| k.as_str()).unwrap_or("unknown");
    match kind {
        "known" => {
            let value = v.get("value").and_then(|v| v.as_bool()).unwrap_or(false);
            TempStateKind::Known(value)
        }
        "parameter-dependent" => {
            let idx = v
                .get("parameterIndex")
                .and_then(|i| i.as_u64())
                .unwrap_or(0) as u32;
            TempStateKind::ParameterDependent(idx)
        }
        _ => TempStateKind::Unknown,
    }
}
