//! R3a-3 Task 2 — capability CONE + COVERAGE vector parity (TDD).
//!
//! Loads the committed `tests/r3a3-vectors/r3a3-vectors.json` (generated by the
//! real al-sem L4: `indexWorkspace → resolveModel → buildCombinedGraph →
//! computeSummaries → projectR3a3`; captured POST-computeSummaries, no dep hooks)
//! and asserts, for each PIPELINE vector, that the Rust `project_r3a3` output's
//! `summaries` array matches the expected projection BYTE-FOR-BYTE (as JSON
//! values).
//!
//! The vectors are the ORACLE: a failure means the Rust port diverged from
//! al-sem — the fix is in the Rust code (NEVER the vector). A mismatch on the
//! `equal_distance_tie` vector is a real tie-breaker bug.

use al_sem::engine::l4::capability_cone::project_r3a3;
use al_sem::program::model::program_calls::assemble_and_resolve_inline_program as assemble_and_resolve;
use serde_json::Value;

const MODEL_INSTANCE_ID: &str = "r0";

#[derive(serde::Deserialize)]
struct VectorsDoc {
    #[serde(rename = "appGuid")]
    app_guid: String,
    #[serde(rename = "pipelineVectors")]
    pipeline_vectors: Vec<PipelineVector>,
}

#[derive(serde::Deserialize)]
struct PipelineVector {
    name: String,
    files: Vec<Vec<String>>,
    expected: PipelineExpected,
}

#[derive(serde::Deserialize)]
struct PipelineExpected {
    summaries: Vec<Value>,
}

fn load_vectors() -> VectorsDoc {
    let raw = include_str!("../r3a3-vectors/r3a3-vectors.json");
    serde_json::from_str(raw).expect("r3a3-vectors.json parses into VectorsDoc")
}

/// The vector's files for the program-backed builder (engine-switch S9.5c),
/// which reads only `.al` files: a fixture name without the extension gets it.
fn files_of(files: &[Vec<String>]) -> Vec<(String, String)> {
    files
        .iter()
        .map(|pair| {
            assert_eq!(pair.len(), 2, "each file entry is [name, source]");
            let name = if pair[0].ends_with(".al") {
                pair[0].clone()
            } else {
                format!("{}.al", pair[0])
            };
            (name, pair[1].clone())
        })
        .collect()
}

#[test]
fn all_r3a3_pipeline_vectors_match() {
    let doc = load_vectors();
    let mut failures: Vec<String> = Vec::new();
    let mut replayed = 0usize;

    for vec in &doc.pipeline_vectors {
        replayed += 1;
        let files = files_of(&vec.files);
        let resolved = assemble_and_resolve(&files, &doc.app_guid, MODEL_INSTANCE_ID);
        let projection = project_r3a3(&resolved);

        let actual_summaries = serde_json::to_value(&projection.summaries).unwrap();
        let expected_summaries = Value::Array(vec.expected.summaries.clone());

        if actual_summaries != expected_summaries {
            failures.push(format!(
                "[{}] summaries mismatch\n  expected: {}\n  actual:   {}",
                vec.name,
                serde_json::to_string_pretty(&expected_summaries).unwrap(),
                serde_json::to_string_pretty(&actual_summaries).unwrap()
            ));
        }
    }

    assert_eq!(replayed, 4, "expected to replay all 4 pipeline vectors");
    assert!(
        failures.is_empty(),
        "R3a-3 cone+coverage pipeline vector parity failures ({}):\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}

/// The equal-distance tie-breaker must be DETERMINISTIC: re-running the same
/// `equal_distance_tie` vector yields the identical inherited witness (HashMap
/// iteration must never leak into the cone output). Locks the tie winner against
/// accidental nondeterminism in the cone walk.
#[test]
fn equal_distance_tie_is_deterministic() {
    let doc = load_vectors();
    let vec = doc
        .pipeline_vectors
        .iter()
        .find(|v| v.name == "equal_distance_tie")
        .expect("equal_distance_tie vector present");
    let files = files_of(&vec.files);

    let first = {
        let resolved = assemble_and_resolve(&files, &doc.app_guid, MODEL_INSTANCE_ID);
        serde_json::to_value(project_r3a3(&resolved).summaries).unwrap()
    };
    // 16 independent re-runs — any HashMap-iteration leak surfaces as a flake.
    for _ in 0..16 {
        let resolved = assemble_and_resolve(&files, &doc.app_guid, MODEL_INSTANCE_ID);
        let again = serde_json::to_value(project_r3a3(&resolved).summaries).unwrap();
        assert_eq!(again, first, "equal-distance tie winner is not stable");
    }
}
