//! R3a-4 Task 2 — dependency-artifact PRODUCER + CONSUMER-hook vector parity (TDD).
//!
//! Loads the committed `tests/r3a4-vectors/r3a4-vectors.json` (generated by the
//! real al-sem dep-hook pipeline: `indexWorkspace → resolveDependencyArtifacts →
//! withDependencyArtifacts → resolveModel → buildCombinedGraph →
//! injectIntraAppCallEdges / collectCitedDepEvidence / collectDepOrderIndex`,
//! projected by `scripts/r3a4-projection.ts`) and asserts the Rust port reproduces:
//!
//!   1. The dep-artifact PRODUCER payload COUNTS for the chain-dep fixture
//!      (`intraAppCallEdgesCount` / `injectedTypedEdgesCount` / `citedEvidenceCount`
//!      / `orderEntriesCount` / `returnSummariesCount` / `depOrderIndexPresent` /
//!      `freshnessStampFresh`) — the main fixture vector.
//!   2. The intraAppCallEdge DEDUP structural invariant (`edgeDedupVector`): ≥1
//!      edge, NO two edges share `(from, to)`, ≥1 injected edge.
//!   3. The freshness-stamp BARRIER (`freshnessVector`): the 6 fresh/stale cases
//!      replayed through `is_dep_order_index_stamp_fresh`.
//!   4. The INJECTION (`injectionVector`): each intraAppCallEdge with both ends in
//!      the merged model becomes one synthetic direct-call typed edge; all injected
//!      edges carry `syntaxKind == "synthetic"`.
//!
//! The vectors are the ORACLE: a mismatch means the Rust port diverged from al-sem
//! — the fix is in the Rust code (NEVER the vector). Task 2 proves the PRODUCER /
//! CONSUMER LOGIC at vector parity; the exact `dep:<artifactKey>` id-string
//! differential vs the goldens is Task 3.

use al_sem::engine::deps::dep_artifact_l4::{
    ConsumerModel, DEP_ORDER_INDEX_SCHEMA_VERSION, DepOrderIndexStamp, collect_cited_dep_evidence,
    collect_dep_order_index, inject_intra_app_call_edges, is_dep_order_index_stamp_fresh,
};
use serde_json::Value;
use std::path::PathBuf;

const MODEL_INSTANCE_ID: &str = "r0";

/// The chain dependency's artifact, built as the cross-app path builds it
/// (engine-switch S7.5): from the cross-app model of the workspace that depends on
/// it, `tests/r3a4-fixtures/ws`.
fn chain_dep_artifact() -> al_sem::engine::deps::dep_artifact_l4::DependencyArtifactL4 {
    let ws = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/r3a4-fixtures/ws");
    let x = al_sem::engine::l3::program_calls::assemble_and_resolve_cross_app_program(
        &ws,
        MODEL_INSTANCE_ID,
        false,
    )
    .expect("cross-app model");
    al_sem::engine::deps::dep_artifact_l4::dep_artifacts_from_model(&x)
        .into_iter()
        .find(|a| a.header.app_guid.starts_with("cccccccc-0001"))
        .expect("chain-dep artifact")
}

fn load_vectors() -> Value {
    let raw = include_str!("../r3a4-vectors/r3a4-vectors.json");
    serde_json::from_str(raw).expect("r3a4-vectors.json parses")
}

/// Build the chain-dep artifact from the committed `.app` fixture (the embedded
/// source PRODUCER), then drive the CONSUMER hooks over a merged model whose
/// routine-id membership is exactly the dep's own routines (the cross-app L4 path
/// the workspace builds; here the dep is the whole merged routine set so the
/// both-ends-in-model guard admits the dep edges).
fn build_consumed() -> (
    al_sem::engine::deps::dep_artifact_l4::DependencyArtifactL4,
    ConsumerModel,
) {
    let artifact = chain_dep_artifact();

    // The merged model's routine membership = the dep's own routines (so the
    // injection both-ends guard admits every intraAppCallEdge — mirrors the
    // workspace+dep merge where both ends of an intra-dep edge are present).
    let routine_ids: Vec<String> = artifact.abi.routines_ids.clone();
    let mut model = ConsumerModel::with_routine_ids(routine_ids);

    inject_intra_app_call_edges(&mut model, std::slice::from_ref(&artifact));
    collect_cited_dep_evidence(&mut model, std::slice::from_ref(&artifact));
    collect_dep_order_index(&mut model, std::slice::from_ref(&artifact));
    (artifact, model)
}

#[test]
fn fixture_payload_counts_match_vector() {
    let doc = load_vectors();
    let v = &doc["vectors"][0];

    let (artifact, model) = build_consumed();

    // Producer payload counts.
    let intra_app = artifact.abi.intra_app_call_edges.len();
    assert_eq!(
        intra_app,
        v["intraAppCallEdgesCount"].as_u64().unwrap() as usize,
        "intraAppCallEdgesCount"
    );
    let cited = artifact.abi.cited_operation_evidence.len();
    assert_eq!(
        cited,
        v["citedEvidenceCount"].as_u64().unwrap() as usize,
        "citedEvidenceCount (producer)"
    );
    let order_present = artifact.abi.dep_order_index.is_some();
    assert_eq!(
        order_present,
        v["depOrderIndexPresent"].as_bool().unwrap(),
        "depOrderIndexPresent"
    );
    let fresh = artifact
        .abi
        .dep_order_index
        .as_ref()
        .map(|idx| is_dep_order_index_stamp_fresh(&idx.stamp, &artifact.header))
        .unwrap_or(false);
    assert_eq!(
        fresh,
        v["freshnessStampFresh"].as_bool().unwrap(),
        "freshnessStampFresh"
    );

    // Consumed-effect counts.
    assert_eq!(
        model.injected_typed_edges.len(),
        v["injectedTypedEdgesCount"].as_u64().unwrap() as usize,
        "injectedTypedEdgesCount"
    );
    assert_eq!(
        model.cited_dep_operation_evidence.len(),
        v["citedEvidenceCount"].as_u64().unwrap() as usize,
        "citedEvidenceCount (consumer)"
    );
    assert_eq!(
        model.dep_routine_order_entries.len(),
        v["orderEntriesCount"].as_u64().unwrap() as usize,
        "orderEntriesCount"
    );
    assert_eq!(
        model.dep_return_summaries.len(),
        v["returnSummariesCount"].as_u64().unwrap() as usize,
        "returnSummariesCount"
    );
}

#[test]
fn intra_app_call_edge_dedup_invariants() {
    let doc = load_vectors();
    let v = &doc["edgeDedupVector"];
    let (artifact, model) = build_consumed();

    let edges = &artifact.abi.intra_app_call_edges;
    // ≥1 intraAppCallEdge (non-hollow fixture).
    assert!(!edges.is_empty(), "≥1 intraAppCallEdge present");
    // No two edges share (from, to).
    let mut seen = std::collections::HashSet::new();
    for e in edges {
        assert!(
            seen.insert((e.from.clone(), e.to.clone())),
            "dedup invariant: two edges share (from,to) {} -> {}",
            e.from,
            e.to
        );
    }
    // ≥1 injected typed edge.
    assert!(
        !model.injected_typed_edges.is_empty(),
        "≥1 injected typedEdge"
    );

    // Pinned counts.
    assert_eq!(
        edges.len(),
        v["intraAppCallEdgesCount"].as_u64().unwrap() as usize
    );
    assert_eq!(
        model.injected_typed_edges.len(),
        v["injectedTypedEdgesCount"].as_u64().unwrap() as usize
    );

    // Edges sorted by (from, to).
    let mut sorted = edges.clone();
    sorted.sort_by(|a, b| a.from.cmp(&b.from).then(a.to.cmp(&b.to)));
    assert_eq!(*edges, sorted, "intraAppCallEdges sorted by (from,to)");
}

#[test]
fn freshness_stamp_barrier_cases() {
    let doc = load_vectors();
    let v = &doc["freshnessVector"];
    let cases = v["freshCases"].as_array().unwrap();

    let (artifact, _model) = build_consumed();
    let header = &artifact.header;
    let base = artifact
        .abi
        .dep_order_index
        .as_ref()
        .expect("dep order index present")
        .stamp
        .clone();

    // Sanity: the produced base stamp is fresh against its own header
    // (packageSemanticHash is empty in the producer → conservatively fresh).
    assert!(
        is_dep_order_index_stamp_fresh(&base, header),
        "produced base stamp is fresh"
    );

    let mut replayed = 0usize;
    for case in cases {
        let label = case["label"].as_str().unwrap();
        let expected = case["fresh"].as_bool().unwrap();
        replayed += 1;

        let (stamp, hdr_pkg_semantic): (DepOrderIndexStamp, String) = match label {
            "all-match → fresh" => {
                // sourceContentHash matches a NON-empty packageSemanticHash.
                let mut s = base.clone();
                s.source_content_hash = "PKGHASH".to_string();
                (s, "PKGHASH".to_string())
            }
            "wrong appId → stale" => {
                let mut s = base.clone();
                s.app_id = "deadbeef-0000-0000-0000-000000000000".to_string();
                (s, String::new())
            }
            "wrong version → stale" => {
                let mut s = base.clone();
                s.version = "9.9.9.9".to_string();
                (s, String::new())
            }
            "wrong sourceContentHash → stale" => {
                let mut s = base.clone();
                s.source_content_hash = "WRONG".to_string();
                (s, "PKGHASH".to_string())
            }
            "wrong schemaVersion → stale" => {
                let mut s = base.clone();
                s.order_index_schema_version = "999".to_string();
                (s, String::new())
            }
            "empty packageSemanticHash → conservatively fresh" => {
                let mut s = base.clone();
                s.source_content_hash = "anything".to_string();
                (s, String::new())
            }
            other => panic!("unexpected freshness case label: {other}"),
        };

        let mut hdr = header.clone();
        hdr.package_semantic_hash = hdr_pkg_semantic;
        let got = is_dep_order_index_stamp_fresh(&stamp, &hdr);
        assert_eq!(got, expected, "freshness case [{label}]");
    }
    assert_eq!(replayed, 6, "replayed all 6 freshness cases");
}

#[test]
fn injection_both_ends_in_model() {
    let doc = load_vectors();
    let v = &doc["injectionVector"];
    let (artifact, model) = build_consumed();

    // ≥1 intraAppCallEdge with both ends in model.
    let member: std::collections::HashSet<&String> = artifact.abi.routines_ids.iter().collect();
    let both_ends = artifact
        .abi
        .intra_app_call_edges
        .iter()
        .filter(|e| member.contains(&e.from) && member.contains(&e.to))
        .count();
    assert!(
        both_ends >= 1,
        "≥1 intraAppCallEdge with both ends in model"
    );

    // injected edge count == intraAppCallEdges with both ends in model.
    assert_eq!(
        model.injected_typed_edges.len(),
        both_ends,
        "injected count == both-ends-in-model count"
    );

    // all injected edges carry syntaxKind == synthetic.
    for e in &model.injected_typed_edges {
        assert_eq!(e.syntax_kind, "synthetic", "injected edge is synthetic");
    }

    assert_eq!(
        artifact.abi.intra_app_call_edges.len(),
        v["intraAppCallEdgesCount"].as_u64().unwrap() as usize
    );
    assert_eq!(
        model.injected_typed_edges.len(),
        v["injectedTypedEdgesCount"].as_u64().unwrap() as usize
    );
    assert_eq!(
        v["bothEndsInModel"].as_bool().unwrap(),
        both_ends == artifact.abi.intra_app_call_edges.len()
    );
}

/// Edges whose ends are ABSENT from the merged model are silently skipped (the
/// injection both-ends guard). A model with NO matching routine ids injects zero.
#[test]
fn injection_absent_ends_skipped() {
    let artifact = chain_dep_artifact();
    let mut empty_model = ConsumerModel::with_routine_ids(vec!["unrelated/routine".to_string()]);
    inject_intra_app_call_edges(&mut empty_model, std::slice::from_ref(&artifact));
    assert!(
        empty_model.injected_typed_edges.is_empty(),
        "edges with absent ends are skipped"
    );
}

/// The schema-version constant matches al-sem's DEP_ORDER_INDEX_SCHEMA_VERSION.
#[test]
fn schema_version_constant_matches() {
    assert_eq!(DEP_ORDER_INDEX_SCHEMA_VERSION, "1");
}

/// Structural-content parity against the al-sem golden's id-INDEPENDENT fields
/// (the exact `dep:<artifactKey>` id strings are Task 3's differential; here we
/// pin the payload SHAPE the embedded-source pipeline produces — sourceFile,
/// file:line anchor, displayText, controlContext, per-routine order-entry shape,
/// and the return-summary booleans — so a real pipeline divergence surfaces).
#[test]
fn producer_payload_structural_parity_with_golden() {
    let (artifact, model) = build_consumed();

    // header identity (the golden's appGuid / version / summaryMode).
    assert_eq!(
        artifact.header.app_guid,
        "cccccccc-0001-0000-0000-000000000001"
    );
    assert_eq!(artifact.header.version, "1.0.0.0");
    assert_eq!(artifact.header.summary_mode, "full");
    assert_eq!(artifact.header.source_kind, "app-source");

    // cited evidence: the r.Insert witness at line 5, cols 8..22, top-level.
    assert_eq!(artifact.abi.cited_operation_evidence.len(), 1);
    let ev = &artifact.abi.cited_operation_evidence[0];
    assert_eq!(
        ev.source_file,
        "dep:cccccccc-0001-0000-0000-000000000001:DepChain.Codeunit.al"
    );
    assert_eq!(ev.start_line, 5);
    assert_eq!(ev.start_column, 8);
    assert_eq!(ev.end_line, 5);
    assert_eq!(ev.end_column, 22);
    assert_eq!(ev.display_text, "r.Insert");
    assert_eq!(ev.control_context.as_deref(), Some("top-level"));
    // the witness operationId is the table-op's `.../op0`.
    assert!(ev.operation_id.ends_with("/op0"), "op0 witness id");

    // dep order index: 2 routine entries — DoWrite (1 op, 0 callsites, 1 frame) and
    // DoIt (0 ops, 1 callsite, 1 frame). The intraAppCallEdge's `to` is DoWrite.
    let idx = artifact.abi.dep_order_index.as_ref().expect("order index");
    assert_eq!(idx.stamp.app_id, "cccccccc-0001-0000-0000-000000000001");
    assert_eq!(idx.stamp.version, "1.0.0.0");
    assert_eq!(idx.stamp.order_index_schema_version, "1");
    assert_eq!(idx.routines.len(), 2);
    assert_eq!(idx.return_summaries.len(), 2);

    let edge = &artifact.abi.intra_app_call_edges[0];
    let do_write_id = &edge.to; // DoWrite is the callee
    let do_it_id = &edge.from; // DoIt is the caller

    let do_write = idx
        .routines
        .iter()
        .find(|e| &e.routine_id == do_write_id)
        .expect("DoWrite order entry");
    assert_eq!(do_write.scope_frames.len(), 1, "DoWrite 1 frame");
    assert_eq!(do_write.operation_orders.len(), 1, "DoWrite 1 op order");
    assert_eq!(
        do_write.callsite_orders.len(),
        0,
        "DoWrite 0 callsite orders"
    );

    let do_it = idx
        .routines
        .iter()
        .find(|e| &e.routine_id == do_it_id)
        .expect("DoIt order entry");
    assert_eq!(do_it.scope_frames.len(), 1, "DoIt 1 frame");
    assert_eq!(do_it.operation_orders.len(), 0, "DoIt 0 op orders");
    assert_eq!(do_it.callsite_orders.len(), 1, "DoIt 1 callsite order");

    // both return summaries: normal-return true, all-error false, no try, resolved,
    // commit normal.
    for rs in &idx.return_summaries {
        assert!(
            matches!(
                rs.has_normal_return_path,
                al_sem::engine::deps::dep_artifact_l4::TriBool::True
            ),
            "hasNormalReturnPath true"
        );
        assert!(
            matches!(
                rs.all_paths_error,
                al_sem::engine::deps::dep_artifact_l4::TriBool::False
            ),
            "allPathsError false"
        );
        assert!(!rs.has_try_function_boundary);
        assert_eq!(rs.coverage, "resolved");
        assert_eq!(rs.commit_behavior, "normal");
    }

    // injected edge mirrors the intraAppCallEdge (DoIt → DoWrite), callsiteId = cs0.
    assert_eq!(model.injected_typed_edges.len(), 1);
    let inj = &model.injected_typed_edges[0];
    assert_eq!(&inj.from, do_it_id);
    assert_eq!(&inj.to, do_write_id);
    assert!(inj.callsite_id.ends_with("/cs0"), "callsite cs0");
    assert_eq!(inj.kind, "direct-call");
}
