//! R2c Task 2 — L3 EVENT-GRAPH + attribute-accessor vector parity.
//!
//! Loads the committed `tests/r2c-vectors/l3eg-vectors.json` (generated by the
//! real al-sem L3: `indexWorkspace` pre-resolve → `resolveModel` post-resolve/
//! pre-summary → projectL3EventGraph; READ-ONLY, never re-runs buildEventGraph)
//! and asserts:
//!
//!   (a) ATTRIBUTE-ARG-SHAPE PARITY — for each attribute vector, parse the inline
//!       routine's `attributesParsed` and verify the structured AttributeArg shape
//!       (kind/value/qualifier/member) matches al-sem's serialization EXACTLY, then
//!       run the 4 accessors (`find_attribute`/`qualified_arg`/`string_arg`/
//!       `bool_arg`) at the indices the event-graph code reads and compare outputs.
//!
//!   (b) EVENT-GRAPH — for each event-graph vector, assemble + resolve the inline
//!       workspace, `build_event_graph`, project to STABLE id form, and compare the
//!       projected `events[]` + `edges[]` to the expected projection EXACTLY.
//!
//! The vectors are the oracle: a failure means the Rust port diverged from al-sem,
//! and the fix is in the Rust code (never the vector).
//!
//! Reproduction context (from `scripts/gen-l3eg-vectors.ts`):
//!   - appGuid          = "c2c00000-0000-0000-0000-0000000002cc"
//!   - modelInstanceId  = "r0"
//!   - files            = [[name, source], ...]  →  sourceUnitId = "ws:<name>"

use al_sem::engine::l3::l3_workspace::assemble_and_resolve;
use al_sem::program::attributes::{
    AttributeInfo, bool_arg, find_attribute, qualified_arg, string_arg,
};
use serde_json::Value;

const APP_GUID: &str = "c2c00000-0000-0000-0000-0000000002cc";
const MODEL_INSTANCE_ID: &str = "r0";

// ---------------------------------------------------------------------------
// Vector document shapes.
// ---------------------------------------------------------------------------

#[derive(serde::Deserialize)]
struct VectorsDoc {
    #[serde(rename = "attrShapeVectorCount")]
    attr_shape_vector_count: usize,
    #[serde(rename = "eventGraphVectorCount")]
    event_graph_vector_count: usize,
    #[serde(rename = "attrShapeVectors")]
    attr_shape_vectors: Vec<AttrShapeVector>,
    #[serde(rename = "eventGraphVectors")]
    event_graph_vectors: Vec<EventGraphVector>,
}

#[derive(serde::Deserialize)]
struct AttrShapeVector {
    name: String,
    /// The structured `attributesParsed` array (the AttributeInfo shape the Rust
    /// L2 attribute indexing must reproduce). Compared structurally.
    #[serde(rename = "attributesParsed")]
    attributes_parsed: Vec<Value>,
    accessor: Accessor,
}

#[derive(serde::Deserialize)]
struct Accessor {
    #[serde(rename = "findName")]
    find_name: String,
    #[serde(rename = "findPresent")]
    find_present: bool,
    #[serde(rename = "qualifiedArgs")]
    qualified_args: Vec<QualifiedArgCheck>,
    #[serde(rename = "stringArgs")]
    string_args: Vec<StringArgCheck>,
    #[serde(rename = "boolArgs")]
    bool_args: Vec<BoolArgCheck>,
}

#[derive(serde::Deserialize)]
struct QualifiedArgCheck {
    index: usize,
    /// `{ qualifier, member }` or null.
    value: Option<QualifiedValue>,
}

#[derive(serde::Deserialize)]
struct QualifiedValue {
    qualifier: String,
    member: String,
}

#[derive(serde::Deserialize)]
struct StringArgCheck {
    index: usize,
    value: Option<String>,
}

#[derive(serde::Deserialize)]
struct BoolArgCheck {
    index: usize,
    value: Option<bool>,
}

#[derive(serde::Deserialize)]
struct EventGraphVector {
    family: String,
    name: String,
    /// `[[filename, source], ...]`
    files: Vec<Vec<String>>,
    expected: ExpectedGraph,
}

#[derive(serde::Deserialize)]
struct ExpectedGraph {
    events: Vec<Value>,
    edges: Vec<Value>,
}

fn load_vectors() -> VectorsDoc {
    let raw = include_str!("../r2c-vectors/l3eg-vectors.json");
    serde_json::from_str(raw).expect("l3eg-vectors.json parses into VectorsDoc")
}

fn files_of(files: &[Vec<String>]) -> Vec<(String, String)> {
    files
        .iter()
        .map(|pair| {
            assert_eq!(pair.len(), 2, "each file entry is [name, source]");
            (pair[0].clone(), pair[1].clone())
        })
        .collect()
}

/// Deserialize the vector's `attributesParsed` JSON into the Rust `AttributeInfo`
/// representation (the SAME struct the accessors operate on), then re-serialize and
/// compare to the original JSON value structurally — this proves the Rust shape is
/// arg-for-arg parity with al-sem.
fn attribute_info_from_json(v: &[Value]) -> Vec<AttributeInfo> {
    v.iter()
        .map(|a| serde_json::from_value(a.clone()).expect("AttributeInfo deserializes"))
        .collect()
}

// ---------------------------------------------------------------------------
// (a) attribute-arg-shape parity + accessor checks.
// ---------------------------------------------------------------------------

#[test]
fn all_attr_shape_vectors_match() {
    let doc = load_vectors();
    assert_eq!(
        doc.attr_shape_vector_count,
        doc.attr_shape_vectors.len(),
        "attrShapeVectorCount agrees with the array length"
    );

    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.attr_shape_vectors {
        let attrs = attribute_info_from_json(&vec.attributes_parsed);

        // Structural round-trip: re-serializing the parsed AttributeInfo must equal
        // the original JSON (proves kind/value/qualifier/member/text/raw parity).
        let reser: Vec<Value> = attrs
            .iter()
            .map(|a| serde_json::to_value(a).expect("AttributeInfo serializes"))
            .collect();
        if reser != vec.attributes_parsed {
            failures.push(format!(
                "[{}] attributesParsed round-trip mismatch\n  expected: {}\n  actual:   {}",
                vec.name,
                serde_json::to_string(&vec.attributes_parsed).unwrap(),
                serde_json::to_string(&reser).unwrap()
            ));
        }

        // find_attribute.
        let found = find_attribute(&attrs, &vec.accessor.find_name);
        if found.is_some() != vec.accessor.find_present {
            failures.push(format!(
                "[{}] find_attribute({}) present mismatch: expected {}, actual {}",
                vec.name,
                vec.accessor.find_name,
                vec.accessor.find_present,
                found.is_some()
            ));
        }

        // The accessors read the FIRST matching attribute named findName. When absent
        // (find_attribute_miss), the vector still lists qualified/string/bool checks
        // that must all be None — run them against the (absent) attr by synthesizing
        // an empty AttributeInfo so the accessors return None for every index.
        let target = found.cloned().unwrap_or(AttributeInfo {
            name: vec.accessor.find_name.clone(),
            args: Vec::new(),
            raw: String::new(),
        });

        for q in &vec.accessor.qualified_args {
            let got = qualified_arg(&target, q.index);
            let got_pair = got.map(|p| (p.qualifier.clone(), p.member.clone()));
            let exp_pair = q
                .value
                .as_ref()
                .map(|v| (v.qualifier.clone(), v.member.clone()));
            if got_pair != exp_pair {
                failures.push(format!(
                    "[{}] qualified_arg({}) mismatch: expected {:?}, actual {:?}",
                    vec.name, q.index, exp_pair, got_pair
                ));
            }
        }

        for s in &vec.accessor.string_args {
            let got = string_arg(&target, s.index);
            if got.as_deref() != s.value.as_deref() {
                failures.push(format!(
                    "[{}] string_arg({}) mismatch: expected {:?}, actual {:?}",
                    vec.name, s.index, s.value, got
                ));
            }
        }

        for b in &vec.accessor.bool_args {
            let got = bool_arg(&target, b.index);
            if got != b.value {
                failures.push(format!(
                    "[{}] bool_arg({}) mismatch: expected {:?}, actual {:?}",
                    vec.name, b.index, b.value, got
                ));
            }
        }
    }

    assert!(
        failures.is_empty(),
        "attribute-shape parity failures ({}):\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}

// ---------------------------------------------------------------------------
// (b) event-graph parity.
// ---------------------------------------------------------------------------

#[test]
fn all_event_graph_vectors_match() {
    let doc = load_vectors();
    assert_eq!(
        doc.event_graph_vector_count,
        doc.event_graph_vectors.len(),
        "eventGraphVectorCount agrees with the array length"
    );

    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.event_graph_vectors {
        let files = files_of(&vec.files);
        let resolved = assemble_and_resolve(&files, APP_GUID, MODEL_INSTANCE_ID);
        let projection = resolved.project_event_graph();

        // Compare events[] (already sorted by stable id in both projections) as JSON.
        let actual_events = serde_json::to_value(&projection.events).expect("events serialize");
        let expected_events = Value::Array(vec.expected.events.clone());
        if actual_events != expected_events {
            failures.push(format!(
                "[{}] {}: events mismatch\n  expected: {}\n  actual:   {}",
                vec.family,
                vec.name,
                serde_json::to_string_pretty(&expected_events).unwrap(),
                serde_json::to_string_pretty(&actual_events).unwrap()
            ));
        }

        let actual_edges = serde_json::to_value(&projection.edges).expect("edges serialize");
        let expected_edges = Value::Array(vec.expected.edges.clone());
        if actual_edges != expected_edges {
            failures.push(format!(
                "[{}] {}: edges mismatch\n  expected: {}\n  actual:   {}",
                vec.family,
                vec.name,
                serde_json::to_string_pretty(&expected_edges).unwrap(),
                serde_json::to_string_pretty(&actual_edges).unwrap()
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "event-graph vector parity failures ({}):\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}
