//! R1a Task 2 — L2 structural body-walker vector parity.
//!
//! Loads the committed `tests/r1a-vectors/l2-vectors.json` (generated by the
//! real al-sem L2 over inline single-file workspaces) and asserts the Rust body
//! walker reproduces each vector family's `expectedFeatures` EXACTLY.
//!
//! **These vectors were minted from al-sem, and al-sem is RETIRED.** They are
//! now Rust-owned baselines like every other golden here: when this engine is
//! intentionally more accurate than al-sem was, the correct move is to
//! rebaseline the vector, NOT to chase al-sem (CLAUDE.md, "Testing Philosophy
//! & Goldens"). A failure is still a defect until proven otherwise — read the
//! diff and establish WHY it moved before touching this file.
//!
//! Unlike its sibling families this file has NO regen path, so a legitimate
//! rebaseline is edited by hand. Issue #21 did exactly that: `Next` gained an
//! argument list at L2, and two vectors gained an empty `fieldArguments`/
//! `fieldArgumentInfos` pair each.
//!
//! Reproduction context (from `scripts/gen-l2-vectors.ts`):
//!   - app.json id  = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"  (appGuid)
//!   - single file  = src/vec.al  →  sourceUnitId = "ws:src/vec.al"
//!   - modelInstanceId = "r0"

use al_sem::engine::l2::features::PFeatures;
use al_sem::engine::l2::features_for_named_routine;

const APP_GUID: &str = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
const MODEL_INSTANCE_ID: &str = "r0";
const SOURCE_UNIT_ID: &str = "ws:src/vec.al";

#[derive(serde::Deserialize)]
struct VectorsDoc {
    #[serde(rename = "familyCount")]
    family_count: usize,
    vectors: Vec<Vector>,
}

#[derive(serde::Deserialize)]
struct Vector {
    family: String,
    name: String,
    source: String,
    #[serde(rename = "routineName")]
    routine_name: String,
    #[serde(rename = "expectedFeatures")]
    expected_features: PFeatures,
}

fn load_vectors() -> VectorsDoc {
    let raw = include_str!("../r1a-vectors/l2-vectors.json");
    serde_json::from_str(raw).expect("l2-vectors.json parses into VectorsDoc")
}

/// Pretty-print a `PFeatures` as canonical JSON for rich failure diffs.
fn to_json(f: &PFeatures) -> String {
    serde_json::to_string_pretty(f).expect("PFeatures serializes")
}

#[test]
fn all_l2_vector_families_match() {
    let doc = load_vectors();
    assert_eq!(doc.family_count, 14, "expected 14 vector families");
    assert_eq!(doc.vectors.len(), 14, "expected 14 vectors");

    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.vectors {
        let actual = features_for_named_routine(
            &vec.source,
            &vec.routine_name,
            APP_GUID,
            MODEL_INSTANCE_ID,
            SOURCE_UNIT_ID,
        );
        let Some(actual) = actual else {
            failures.push(format!(
                "[{}] {}: routine `{}` not found by the Rust walker",
                vec.family, vec.name, vec.routine_name
            ));
            continue;
        };

        if actual != vec.expected_features {
            // Build a focused diff: serialize both and show the first differing
            // top-level field for locality.
            let expected_json = to_json(&vec.expected_features);
            let actual_json = to_json(&actual);
            failures.push(format!(
                "[{}] {} (routine `{}`) MISMATCH\n--- EXPECTED ---\n{}\n--- ACTUAL ---\n{}",
                vec.family, vec.name, vec.routine_name, expected_json, actual_json
            ));
        }
    }

    if !failures.is_empty() {
        panic!(
            "{} of {} L2 vector(s) failed:\n\n{}",
            failures.len(),
            doc.vectors.len(),
            failures.join("\n\n========================================\n\n")
        );
    }
}
