//! R1d Task 2 — L2 direct-capability extractor vector parity.
//!
//! Loads the committed `tests/r1d-vectors/l2cap-vectors.json` (generated by the
//! REAL al-sem capability extractors — `extractCapabilities` run on PRE-RESOLVE
//! routines, NOT the L4 summary pass) and asserts the Rust port
//! (`program::body::capability::extract_capabilities`) reproduces, for every
//! vector routine:
//!   - the STRIPPED `capabilityFactsDirect` (no `resourceId`/`subject`, nested
//!     `table-field.tableId` deep-stripped, `op:"publish"` excluded),
//!   - the extractor's OWN `status` (CoverageStatus) + `reasons` (CoverageReason[]),
//!   - the index-stage unreachable-exclusion diagnostics.
//!
//! The vectors are the oracle: a failure means the Rust port diverged from
//! al-sem — fix the Rust code, never the vector.
//!
//! Reproduction context (mirrors gen-l2cap-vectors / the other l2 vector tests):
//!   - app.json id     = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"  (appGuid)
//!   - single file     = src/vec.al  →  sourceUnitId = "ws:src/vec.al"
//!   - modelInstanceId = "r0"  (the witness `op*`/`cs*` id prefixes are `r0/<hash>/…`)

use al_sem::program::body::capability::extract_capabilities;
use al_sem::program::body::l2_workspace::project_named_routine;
use std::collections::BTreeMap;

const APP_GUID: &str = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
const SOURCE_UNIT_ID: &str = "ws:src/vec.al";

#[derive(serde::Deserialize)]
struct VectorsDoc {
    #[serde(rename = "familyCount")]
    family_count: usize,
    #[serde(rename = "vectorCount")]
    vector_count: usize,
    vectors: Vec<Vector>,
}

#[derive(serde::Deserialize)]
struct Vector {
    family: String,
    name: String,
    source: String,
    #[serde(rename = "routineName")]
    routine_name: String,
    #[serde(rename = "expectedFacts")]
    expected_facts: Vec<serde_json::Value>,
    #[serde(rename = "expectedStatus")]
    expected_status: String,
    #[serde(rename = "expectedReasons")]
    expected_reasons: Vec<String>,
    #[serde(rename = "expectedDiagnostics")]
    expected_diagnostics: Vec<serde_json::Value>,
}

fn load_vectors() -> VectorsDoc {
    let raw = include_str!("../r1d-vectors/l2cap-vectors.json");
    serde_json::from_str(raw).expect("l2cap-vectors.json parses into VectorsDoc")
}

/// Canonicalize a JSON value into a stable string key for multiset comparison:
/// object keys are sorted recursively. This makes two JSON values that differ
/// only in key order compare equal.
fn canonical(value: &serde_json::Value) -> String {
    fn norm(v: &serde_json::Value) -> serde_json::Value {
        match v {
            serde_json::Value::Object(m) => {
                let sorted: BTreeMap<String, serde_json::Value> =
                    m.iter().map(|(k, vv)| (k.clone(), norm(vv))).collect();
                serde_json::to_value(sorted).unwrap()
            }
            serde_json::Value::Array(a) => serde_json::Value::Array(a.iter().map(norm).collect()),
            other => other.clone(),
        }
    }
    serde_json::to_string(&norm(value)).unwrap()
}

/// Order-insensitive multiset equality of two JSON value lists by canonical key.
fn multiset_eq(a: &[serde_json::Value], b: &[serde_json::Value]) -> bool {
    let mut ca: Vec<String> = a.iter().map(canonical).collect();
    let mut cb: Vec<String> = b.iter().map(canonical).collect();
    ca.sort();
    cb.sort();
    ca == cb
}

fn diff_lines(label: &str, items: &[serde_json::Value]) -> String {
    if items.is_empty() {
        return format!("  {label}: <empty>\n");
    }
    let mut out = format!("  {label}:\n");
    let mut keys: Vec<String> = items.iter().map(canonical).collect();
    keys.sort();
    for k in keys {
        out.push_str(&format!("    {k}\n"));
    }
    out
}

#[test]
fn all_l2cap_vector_families_match() {
    let doc = load_vectors();
    assert_eq!(doc.family_count, 17, "expected 17 vector families");
    assert_eq!(doc.vector_count, 18, "expected 18 vectors");
    assert_eq!(doc.vectors.len(), 18, "expected 18 vectors");

    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.vectors {
        let routine =
            project_named_routine(&vec.source, &vec.routine_name, APP_GUID, SOURCE_UNIT_ID);
        let Some(routine) = routine else {
            failures.push(format!(
                "[{}] {}: routine `{}` not found by the Rust projector",
                vec.family, vec.name, vec.routine_name
            ));
            continue;
        };

        let result = extract_capabilities(&routine);

        // 1) Facts (order-insensitive multiset; al-sem emits in extractor order,
        //    but matching as a multiset is robust + the projection field order is
        //    irrelevant once canonicalized).
        let actual_facts: Vec<serde_json::Value> = result
            .facts
            .iter()
            .map(|f| serde_json::to_value(f).expect("fact serializes"))
            .collect();
        if !multiset_eq(&actual_facts, &vec.expected_facts) {
            failures.push(format!(
                "[{}] {}: capabilityFactsDirect MISMATCH ({} expected, {} actual)\n{}{}",
                vec.family,
                vec.name,
                vec.expected_facts.len(),
                actual_facts.len(),
                diff_lines("expected", &vec.expected_facts),
                diff_lines("actual", &actual_facts),
            ));
        }

        // 2) status.
        if result.status.as_str() != vec.expected_status {
            failures.push(format!(
                "[{}] {}: status MISMATCH expected={:?} actual={:?}",
                vec.family,
                vec.name,
                vec.expected_status,
                result.status.as_str()
            ));
        }

        // 3) reasons (sorted/deduped by the orchestrator; vector is sorted).
        let actual_reasons: Vec<String> = result
            .reasons
            .iter()
            .map(|r| r.as_str().to_string())
            .collect();
        if actual_reasons != vec.expected_reasons {
            failures.push(format!(
                "[{}] {}: reasons MISMATCH expected={:?} actual={:?}",
                vec.family, vec.name, vec.expected_reasons, actual_reasons
            ));
        }

        // 4) diagnostics (index-stage unreachable exclusions). Multiset match.
        let actual_diags: Vec<serde_json::Value> = result
            .diagnostics
            .iter()
            .map(|d| serde_json::to_value(d).expect("diagnostic serializes"))
            .collect();
        if !multiset_eq(&actual_diags, &vec.expected_diagnostics) {
            failures.push(format!(
                "[{}] {}: diagnostics MISMATCH\n{}{}",
                vec.family,
                vec.name,
                diff_lines("expected", &vec.expected_diagnostics),
                diff_lines("actual", &actual_diags),
            ));
        }
    }

    if !failures.is_empty() {
        panic!(
            "{} L2 capability assertion(s) failed:\n\n{}",
            failures.len(),
            failures.join("\n\n")
        );
    }
}
