//! R1b Task 2 — L2 control-context lattice vector parity.
//!
//! Loads the committed `tests/r1b-vectors/l2cc-vectors.json` (generated by the
//! real al-sem L2 control-context walker — `computeControlContexts` inside
//! `indexRoutines`, INCLUDING the error-call source-range post-pass) and asserts
//! the Rust port (`control_flow.rs` + `control_context.rs`) reproduces, for every
//! site, the expected `controlContext` (ABSENT == None) and the computed
//! IsHandled-eligibility set.
//!
//! The vectors are the oracle: a failure means the Rust port diverged from
//! al-sem — fix the Rust code, never the vector.
//!
//! Reproduction context (mirrors gen-l2cc-vectors / gen-l2-vectors):
//!   - app.json id  = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"  (appGuid)
//!   - single file  = src/vec.al  →  sourceUnitId = "ws:src/vec.al"
//!   - modelInstanceId = "r0"

use al_sem::program::body::control_context::{ControlContext, analyze_named_routine};
use std::collections::BTreeSet;

const APP_GUID: &str = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
const MODEL_INSTANCE_ID: &str = "r0";
const SOURCE_UNIT_ID: &str = "ws:src/vec.al";

#[derive(serde::Deserialize)]
struct VectorsDoc {
    #[serde(rename = "familyCount")]
    family_count: usize,
    #[serde(rename = "vectorCount")]
    vector_count: usize,
    vectors: Vec<Vector>,
}

#[derive(serde::Deserialize)]
struct Vector {
    family: String,
    name: String,
    source: String,
    #[serde(rename = "routineName")]
    routine_name: String,
    sites: Vec<SiteExpect>,
    #[serde(rename = "isHandledEligibility")]
    is_handled_eligibility: EligibilityExpect,
}

#[derive(serde::Deserialize)]
struct SiteExpect {
    category: String,
    #[allow(dead_code)]
    label: String,
    #[serde(rename = "startLine")]
    start_line: u32,
    #[serde(rename = "startColumn")]
    start_column: u32,
    /// Absent (key omitted) == None == al-sem left controlContext undefined.
    #[serde(rename = "controlContext")]
    control_context: Option<String>,
}

#[derive(serde::Deserialize)]
struct EligibilityExpect {
    #[serde(rename = "byVarBoolParams")]
    by_var_bool_params: Vec<String>,
    #[serde(rename = "publishedBoolVars")]
    published_bool_vars: Vec<String>,
    all: Vec<String>,
}

fn load_vectors() -> VectorsDoc {
    let raw = include_str!("../r1b-vectors/l2cc-vectors.json");
    serde_json::from_str(raw).expect("l2cc-vectors.json parses into VectorsDoc")
}

fn ctx_str(c: ControlContext) -> &'static str {
    match c {
        ControlContext::TopLevel => "top-level",
        ControlContext::Conditional => "conditional",
        ControlContext::LoopBody => "loop-body",
        ControlContext::IsHandledGuarded => "is-handled-guarded",
        ControlContext::ErrorPath => "error-path",
        ControlContext::Unreachable => "unreachable",
    }
}

#[test]
fn all_l2cc_vector_families_match() {
    let doc = load_vectors();
    assert_eq!(doc.family_count, 7, "expected 7 vector families");
    assert_eq!(doc.vector_count, 13, "expected 13 vectors");
    assert_eq!(doc.vectors.len(), 13, "expected 13 vectors");

    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.vectors {
        let analysis = analyze_named_routine(
            &vec.source,
            &vec.routine_name,
            APP_GUID,
            MODEL_INSTANCE_ID,
            SOURCE_UNIT_ID,
        );
        let Some(analysis) = analysis else {
            failures.push(format!(
                "[{}] {}: routine `{}` not found by the Rust walker",
                vec.family, vec.name, vec.routine_name
            ));
            continue;
        };

        // 1) IsHandled eligibility set parity (debug side field).
        let exp_byvar: BTreeSet<String> = vec
            .is_handled_eligibility
            .by_var_bool_params
            .iter()
            .cloned()
            .collect();
        let exp_pub: BTreeSet<String> = vec
            .is_handled_eligibility
            .published_bool_vars
            .iter()
            .cloned()
            .collect();
        let exp_all: BTreeSet<String> = vec.is_handled_eligibility.all.iter().cloned().collect();
        let act_byvar: BTreeSet<String> = analysis
            .eligibility
            .by_var_bool_params
            .iter()
            .cloned()
            .collect();
        let act_pub: BTreeSet<String> = analysis
            .eligibility
            .published_bool_vars
            .iter()
            .cloned()
            .collect();
        let act_all: BTreeSet<String> = act_byvar.union(&act_pub).cloned().collect();
        if act_byvar != exp_byvar || act_pub != exp_pub || act_all != exp_all {
            failures.push(format!(
                "[{}] {}: IsHandled eligibility MISMATCH\n  byVar expected={:?} actual={:?}\n  published expected={:?} actual={:?}\n  all expected={:?} actual={:?}",
                vec.family, vec.name, exp_byvar, act_byvar, exp_pub, act_pub, exp_all, act_all
            ));
        }

        // 2) Per-site controlContext parity (absent == None).
        for site in &vec.sites {
            // Resolve the site's id by matching the anchor (startLine/startColumn)
            // against the projected call/operation sites.
            let actual: Option<&'static str> = if site.category == "callsite" {
                analysis
                    .call_sites
                    .iter()
                    .find(|cs| {
                        cs.source_anchor.start_line == site.start_line
                            && cs.source_anchor.start_column == site.start_column
                    })
                    .and_then(|cs| analysis.by_callsite.get(&cs.id).copied())
                    .map(ctx_str)
            } else {
                // operation: match on the op's source anchor. error-call ops and
                // record-ops/commit ops alike live in operation_sites; the
                // post-pass already folded error-call inheritance into by_operation.
                analysis
                    .operation_sites
                    .iter()
                    .find(|op| {
                        op.source_anchor.start_line == site.start_line
                            && op.source_anchor.start_column == site.start_column
                            && site_kind_matches(&site.label, &op.kind)
                    })
                    .and_then(|op| analysis.by_operation.get(&op.id).copied())
                    .map(ctx_str)
            };
            let expected = site.control_context.as_deref();
            if actual != expected {
                failures.push(format!(
                    "[{}] {}: site {} `{}` @ {}:{} controlContext MISMATCH expected={:?} actual={:?}",
                    vec.family,
                    vec.name,
                    site.category,
                    site.label,
                    site.start_line,
                    site.start_column,
                    expected,
                    actual
                ));
            }
        }
    }

    if !failures.is_empty() {
        panic!(
            "{} L2 control-context assertion(s) failed:\n\n{}",
            failures.len(),
            failures.join("\n\n")
        );
    }
}

/// A site label disambiguates two operation sites that may share an anchor
/// (e.g. the Error() callsite anchor coincides with the `error-call` op anchor;
/// they are distinguished by category, so within operation_sites this only needs
/// to keep `error-call` matching the right op when a record-op shares the line).
fn site_kind_matches(label: &str, op_kind: &str) -> bool {
    match label {
        "error-call" => op_kind == "error-call",
        "commit" => op_kind == "commit",
        // record-op vectors target record operations projected as operation sites
        // of various kinds (find/modify/insert/delete/...). Any non-error/commit
        // op kind is acceptable at a unique anchor.
        _ => op_kind != "error-call",
    }
}
