//! R1c Task 2 — L2 operation-order walk vector parity.
//!
//! Loads the committed `tests/r1c-vectors/l2order-vectors.json` (generated by the
//! real al-sem L2 operation-order walker — `computeOperationOrder` inside
//! `indexRoutines`, INCLUDING the error-call source-range order post-pass) and
//! asserts the Rust port (`operation_order.rs`, reusing `control_flow.rs`)
//! reproduces, for every site, the expected `order` (OperationOrder; ABSENT ==
//! None) AND the routine's positional `scopeFrames` table.
//!
//! The vectors are the oracle: a failure means the Rust port diverged from
//! al-sem — fix the Rust code, never the vector.
//!
//! Reproduction context (mirrors gen-l2order-vectors / l2cc_vectors):
//!   - app.json id    = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"  (appGuid)
//!   - single file    = src/vec.al  →  sourceUnitId = "ws:src/vec.al"
//!   - modelInstanceId = "r0"

use al_sem::program::body::operation_order::{OperationOrder, analyze_named_routine_order};

const APP_GUID: &str = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
const MODEL_INSTANCE_ID: &str = "r0";
const SOURCE_UNIT_ID: &str = "ws:src/vec.al";

#[derive(serde::Deserialize)]
struct VectorsDoc {
    #[serde(rename = "familyCount")]
    family_count: usize,
    #[serde(rename = "vectorCount")]
    vector_count: usize,
    vectors: Vec<Vector>,
}

#[derive(serde::Deserialize)]
struct Vector {
    family: String,
    name: String,
    source: String,
    #[serde(rename = "routineName")]
    routine_name: String,
    sites: Vec<SiteExpect>,
    #[serde(rename = "scopeFrames")]
    scope_frames: Vec<FrameExpect>,
}

#[derive(serde::Deserialize)]
struct SiteExpect {
    category: String,
    label: String,
    #[serde(rename = "startLine")]
    start_line: u32,
    #[serde(rename = "startColumn")]
    start_column: u32,
    /// Absent (key omitted) == None == al-sem left `order` undefined.
    order: Option<OrderExpect>,
}

#[derive(serde::Deserialize, Debug, Clone, PartialEq, Eq)]
struct OrderExpect {
    #[serde(rename = "orderId")]
    order_id: u32,
    #[serde(rename = "frameId")]
    frame_id: i64,
    #[serde(rename = "onSuccessPath")]
    on_success_path: bool,
    #[serde(rename = "dominatesSuccessReturn")]
    dominates_success_return: bool,
}

#[derive(serde::Deserialize, Debug, Clone, PartialEq, Eq)]
struct FrameExpect {
    #[serde(rename = "frameId")]
    frame_id: i64,
    #[serde(rename = "parentFrameId")]
    parent_frame_id: i64,
    kind: String,
    /// Branch frames carry these even when false; root/loop/try OMIT them (None).
    #[serde(rename = "branchAlwaysTerminates")]
    branch_always_terminates: Option<bool>,
    #[serde(rename = "branchTerminatesBy")]
    branch_terminates_by: Option<String>,
    #[serde(rename = "branchMayFallThrough")]
    branch_may_fall_through: Option<bool>,
}

fn load_vectors() -> VectorsDoc {
    let raw = include_str!("../r1c-vectors/l2order-vectors.json");
    serde_json::from_str(raw).expect("l2order-vectors.json parses into VectorsDoc")
}

fn order_to_expect(o: &OperationOrder) -> OrderExpect {
    OrderExpect {
        order_id: o.order_id,
        frame_id: o.frame_id,
        on_success_path: o.on_success_path,
        dominates_success_return: o.dominates_success_return,
    }
}

/// A site label disambiguates two operation sites that may share an anchor
/// (the Error() callsite anchor coincides with the `error-call` op anchor; they
/// are distinguished by category, but within operation_sites the `error-call` op
/// and a record-op could share a line). Mirrors `l2cc_vectors::site_kind_matches`.
fn site_kind_matches(label: &str, op_kind: &str) -> bool {
    match label {
        "error-call" => op_kind == "error-call",
        "commit" => op_kind == "commit",
        _ => op_kind != "error-call",
    }
}

#[test]
fn all_l2order_vector_families_match() {
    let doc = load_vectors();
    assert_eq!(doc.family_count, 7, "expected 7 vector families");
    assert_eq!(doc.vector_count, 16, "expected 16 vectors");
    assert_eq!(doc.vectors.len(), 16, "expected 16 vectors");

    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.vectors {
        let analysis = analyze_named_routine_order(
            &vec.source,
            &vec.routine_name,
            APP_GUID,
            MODEL_INSTANCE_ID,
            SOURCE_UNIT_ID,
        );
        let Some(analysis) = analysis else {
            failures.push(format!(
                "[{}] {}: routine `{}` not found by the Rust walker",
                vec.family, vec.name, vec.routine_name
            ));
            continue;
        };

        // 1) ScopeFrame table parity (positional).
        if analysis.scope_frames.len() != vec.scope_frames.len() {
            failures.push(format!(
                "[{}] {}: scopeFrames LENGTH MISMATCH expected={} actual={}\n  expected={:?}\n  actual={:?}",
                vec.family,
                vec.name,
                vec.scope_frames.len(),
                analysis.scope_frames.len(),
                vec.scope_frames,
                analysis.scope_frames,
            ));
        } else {
            for (i, (exp, act)) in vec
                .scope_frames
                .iter()
                .zip(analysis.scope_frames.iter())
                .enumerate()
            {
                let act_exp = FrameExpect {
                    frame_id: act.frame_id,
                    parent_frame_id: act.parent_frame_id,
                    kind: act.kind.clone(),
                    branch_always_terminates: act.branch_always_terminates,
                    branch_terminates_by: act.branch_terminates_by.clone(),
                    branch_may_fall_through: act.branch_may_fall_through,
                };
                if &act_exp != exp {
                    failures.push(format!(
                        "[{}] {}: scopeFrame[{}] MISMATCH\n  expected={:?}\n  actual={:?}",
                        vec.family, vec.name, i, exp, act_exp
                    ));
                }
            }
        }

        // 2) Per-site `order` parity (absent == None).
        for site in &vec.sites {
            let actual: Option<OrderExpect> = if site.category == "callsite" {
                analysis
                    .call_sites
                    .iter()
                    .find(|cs| {
                        cs.source_anchor.start_line == site.start_line
                            && cs.source_anchor.start_column == site.start_column
                    })
                    .and_then(|cs| analysis.by_callsite.get(&cs.id))
                    .map(order_to_expect)
            } else {
                analysis
                    .operation_sites
                    .iter()
                    .find(|op| {
                        op.source_anchor.start_line == site.start_line
                            && op.source_anchor.start_column == site.start_column
                            && site_kind_matches(&site.label, &op.kind)
                    })
                    .and_then(|op| analysis.by_operation.get(&op.id))
                    .map(order_to_expect)
            };
            let expected = site.order.clone();
            if actual != expected {
                failures.push(format!(
                    "[{}] {}: site {} `{}` @ {}:{} order MISMATCH\n  expected={:?}\n  actual={:?}",
                    vec.family,
                    vec.name,
                    site.category,
                    site.label,
                    site.start_line,
                    site.start_column,
                    expected,
                    actual
                ));
            }
        }
    }

    if !failures.is_empty() {
        panic!(
            "{} L2 operation-order assertion(s) failed:\n\n{}",
            failures.len(),
            failures.join("\n\n")
        );
    }
}
